import assert from "node:assert/strict";
import { createLintRefreshQueue } from "./lintRefreshQueue.ts";

const tick = () => new Promise((resolve) => setImmediate(resolve));
const requests = [];
const queue = createLintRefreshQueue(() => new Promise((resolve, reject) => requests.push({ resolve, reject })));
const initial = queue.refresh();
let dismissed = false;
const a = queue.refresh().then(() => { dismissed = true; });
const b = queue.refresh();
assert.equal(requests.length, 1);
requests[0].resolve();
await initial;
await tick();
assert.equal(dismissed, false, "dismiss must await a request started after invalidation");
assert.equal(requests.length, 2, "burst produces only one follow-up");
const c = queue.refresh();
requests[1].reject(new Error("network"));
await Promise.all([a, b]);
await tick();
assert.equal(requests.length, 3, "failure does not strand the next invalidation");
requests[2].resolve();
await c;
const d = queue.refresh();
const pending = queue.refresh();
queue.dispose();
await pending;
requests[3].resolve();
await d;
await queue.refresh();
assert.equal(requests.length, 4, "disposal prevents old-book queued requests");
console.log("lint refresh queue: fresh dismiss, coalescing, failure, disposal passed");
