// Backfill chapter-front (verse=0) rows that an earlier importer dropped.
//
// The original scripts/import-book.mjs (and the on-demand auto-importer
// prior to PR #36) skipped the `front` key when extracting from usfm-js,
// which holds chapter-leading markers like `\p` and `\s1` that appear
// before the first `\v`. The nightly export then emits chapters without
// those markers, producing the en_ust master...live-snapshot diff.
//
// This script is the one-off data fix. It fetches each book's source
// USFM from DCS, extracts only the chapter-front content (verse=0), and
// emits `INSERT OR IGNORE` rows. `OR IGNORE` makes it safe to run when
// some verse 0 rows already exist (e.g. UHB for NUM).
//
// Usage from repo root:
//   node scripts/backfill-verse0.mjs              # all books
//   node scripts/backfill-verse0.mjs NUM EXO LEV  # selected books
// Then apply:
//   (cd api && npx wrangler d1 execute bible_editor --remote --env production \
//       --file=../scripts/out/backfill-verse0.sql)
//
// Apply locally first to verify the diff is sane:
//   (cd api && npx wrangler d1 execute bible_editor --local \
//       --file=../scripts/out/backfill-verse0.sql)

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import usfm from "usfm-js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const BOOK_NUMBERS = {
  GEN: "01", EXO: "02", LEV: "03", NUM: "04", DEU: "05", JOS: "06", JDG: "07",
  RUT: "08", "1SA": "09", "2SA": "10", "1KI": "11", "2KI": "12", "1CH": "13",
  "2CH": "14", EZR: "15", NEH: "16", EST: "17", JOB: "18", PSA: "19",
  PRO: "20", ECC: "21", SNG: "22", ISA: "23", JER: "24", LAM: "25",
  EZK: "26", DAN: "27", HOS: "28", JOL: "29", AMO: "30", OBA: "31",
  JON: "32", MIC: "33", NAM: "34", HAB: "35", ZEP: "36", HAG: "37",
  ZEC: "38", MAL: "39",
  MAT: "41", MRK: "42", LUK: "43", JHN: "44", ACT: "45",
  ROM: "46", "1CO": "47", "2CO": "48", GAL: "49", EPH: "50",
  PHP: "51", COL: "52", "1TH": "53", "2TH": "54", "1TI": "55",
  "2TI": "56", TIT: "57", PHM: "58", HEB: "59", JAS: "60",
  "1PE": "61", "2PE": "62", "1JN": "63", "2JN": "64", "3JN": "65",
  JUD: "66", REV: "67",
};

const NT_BOOKS = new Set([
  "MAT", "MRK", "LUK", "JHN", "ACT", "ROM", "1CO", "2CO", "GAL", "EPH",
  "PHP", "COL", "1TH", "2TH", "1TI", "2TI", "TIT", "PHM", "HEB", "JAS",
  "1PE", "2PE", "1JN", "2JN", "3JN", "JUD", "REV",
]);

const DCS_BASE = "https://git.door43.org";

const argv = process.argv.slice(2);
const books = argv.length > 0
  ? argv.map((b) => b.toUpperCase())
  : Object.keys(BOOK_NUMBERS);

const q = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

function extractPlainText(verseObj) {
  const parts = [];
  const walk = (vos) => {
    for (const vo of vos || []) {
      if (!vo || typeof vo !== "object") continue;
      if (typeof vo.text === "string") parts.push(vo.text);
      if (Array.isArray(vo.children)) walk(vo.children);
    }
  };
  walk(verseObj?.verseObjects ?? []);
  return parts.join("").replace(/\s+/g, " ").trim();
}

async function fetchText(url) {
  const r = await fetch(url);
  if (!r.ok) return null;
  return await r.text();
}

async function frontRowsFor(book, num, bibleVersion, repo) {
  const url = `${DCS_BASE}/unfoldingWord/${repo}/raw/branch/master/${num}-${book}.usfm`;
  const raw = await fetchText(url);
  if (!raw) {
    console.warn(`  · ${book} ${bibleVersion}: source not fetched (${url})`);
    return [];
  }
  const json = usfm.toJSON(raw);
  const out = [];
  for (const chapterKey of Object.keys(json.chapters ?? {})) {
    const chNum = parseInt(chapterKey, 10);
    if (!Number.isFinite(chNum)) continue;
    const chapterObj = json.chapters[chapterKey];
    const front = chapterObj?.front;
    if (!front) continue;
    const objs = Array.isArray(front.verseObjects) ? front.verseObjects : [];
    if (objs.length === 0) continue;
    out.push({
      book,
      chapter: chNum,
      verse: 0,
      verse_end: null,
      bible_version: bibleVersion,
      content_json: JSON.stringify(front),
      plain_text: extractPlainText(front),
    });
  }
  return out;
}

const lines = [];
lines.push("-- Auto-generated by scripts/backfill-verse0.mjs. Do not edit by hand.");
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push(`-- Books: ${books.join(", ")}`);
lines.push("");

let total = 0;
for (const book of books) {
  const num = BOOK_NUMBERS[book];
  if (!num) {
    console.warn(`skipping unknown book: ${book}`);
    continue;
  }
  const origRepo = NT_BOOKS.has(book) ? "el-x-koine_ugnt" : "hbo_uhb";
  const origVersion = NT_BOOKS.has(book) ? "UGNT" : "UHB";

  const [ult, ust, orig] = await Promise.all([
    frontRowsFor(book, num, "ULT", "en_ult"),
    frontRowsFor(book, num, "UST", "en_ust"),
    frontRowsFor(book, num, origVersion, origRepo),
  ]);
  const all = [...ult, ...ust, ...orig];
  if (all.length === 0) continue;

  lines.push(`-- ${book}: ${all.length} verse-0 rows`);
  for (const r of all) {
    lines.push(
      `INSERT OR IGNORE INTO verses (book, chapter, verse, verse_end, bible_version, content_json, plain_text) VALUES (${q(r.book)}, ${q(r.chapter)}, ${q(r.verse)}, ${q(r.verse_end)}, ${q(r.bible_version)}, ${q(r.content_json)}, ${q(r.plain_text)});`,
    );
  }
  total += all.length;
  console.log(`  · ${book}: ${ult.length} ULT, ${ust.length} UST, ${orig.length} ${origVersion}`);
}

const outDir = resolve(repoRoot, "scripts/out");
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
const outFile = resolve(outDir, "backfill-verse0.sql");
writeFileSync(outFile, lines.join("\n") + "\n", "utf8");
console.log(`\nWrote ${total} INSERT OR IGNORE statements to ${outFile}`);
