// One-shot importer. Reads a book's ULT/UST/UHB USFM and tn/tq/twl TSVs
// from docs/samples/ and emits a SQL file with INSERT statements for the D1
// schema (api/migrations/0001_init.sql).
//
// Run:
//   node scripts/import-book.mjs ZEC
// Then apply:
//   (cd api && npx wrangler d1 execute bible_editor --local --file=../scripts/out/import-ZEC.sql)
//
// The emitter is idempotent only at the row level (REPLACE INTO). Re-running
// for the same book will overwrite existing rows; the version stamp resets
// to 1, so don't re-import a book that already has editor work in it.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import usfm from "usfm-js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const book = (process.argv[2] || "").toUpperCase();
if (!book) {
  console.error("usage: node scripts/import-book.mjs <BOOK_CODE>   e.g. ZEC");
  process.exit(1);
}

// Standard unfoldingWord book number prefixes for USFM filenames.
const BOOK_NUMBERS = {
  GEN: "01", EXO: "02", LEV: "03", NUM: "04", DEU: "05", JOS: "06", JDG: "07",
  RUT: "08", "1SA": "09", "2SA": "10", "1KI": "11", "2KI": "12", "1CH": "13",
  "2CH": "14", EZR: "15", NEH: "16", EST: "17", JOB: "18", PSA: "19",
  PRO: "20", ECC: "21", SNG: "22", ISA: "23", JER: "24", LAM: "25",
  EZK: "26", DAN: "27", HOS: "28", JOL: "29", AMO: "30", OBA: "31",
  JON: "32", MIC: "33", NAM: "34", HAB: "35", ZEP: "36", HAG: "37",
  ZEC: "38", MAL: "39",
  MAT: "41", MRK: "42", LUK: "43", JHN: "44", ACT: "45",
  ROM: "46", "1CO": "47", "2CO": "48", GAL: "49", EPH: "50",
  PHP: "51", COL: "52", "1TH": "53", "2TH": "54", "1TI": "55",
  "2TI": "56", TIT: "57", PHM: "58", HEB: "59", JAS: "60",
  "1PE": "61", "2PE": "62", "1JN": "63", "2JN": "64", "3JN": "65",
  JUD: "66", REV: "67",
};

const num = BOOK_NUMBERS[book];
if (!num) {
  console.error(`unknown book code: ${book}`);
  process.exit(1);
}

const samples = resolve(repoRoot, "docs/samples");
const sources = {
  ULT: resolve(samples, `en_ult_${num}-${book}.usfm`),
  UST: resolve(samples, `en_ust_${num}-${book}.usfm`),
  UHB: resolve(samples, `hbo_uhb_${num}-${book}.usfm`),
  tn: resolve(samples, `en_tn_tn_${book}.tsv`),
  tq: resolve(samples, `en_tq_tq_${book}.tsv`),
  twl: resolve(samples, `en_twl_twl_${book}.tsv`),
};

for (const [k, p] of Object.entries(sources)) {
  if (!existsSync(p)) console.warn(`  · missing ${k}: ${p}`);
}

// ---------- SQL escape helpers ----------
const q = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

const lines = [];
lines.push("-- Auto-generated by scripts/import-book.mjs. Do not edit by hand.");
lines.push(`-- Book: ${book}`);
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push("BEGIN TRANSACTION;");

// Wipe existing rows for this book so re-imports are clean. Real edits
// shouldn't have happened yet in v0; if they have, don't re-import.
lines.push(`DELETE FROM tn_rows  WHERE book = ${q(book)};`);
lines.push(`DELETE FROM tq_rows  WHERE book = ${q(book)};`);
lines.push(`DELETE FROM twl_rows WHERE book = ${q(book)};`);
lines.push(`DELETE FROM verses   WHERE book = ${q(book)};`);

// ---------- USFM verses ----------
function importVerses(bibleVersion, srcPath) {
  if (!existsSync(srcPath)) return 0;
  const raw = readFileSync(srcPath, "utf8");
  const json = usfm.toJSON(raw);
  let count = 0;
  for (const chapter of Object.keys(json.chapters || {})) {
    const chNum = parseInt(chapter, 10);
    if (Number.isNaN(chNum)) continue;
    const chapterObj = json.chapters[chapter];
    for (const verse of Object.keys(chapterObj)) {
      if (!/^\d+(-\d+)?$/.test(verse)) continue; // skip 'front', etc.
      const vNum = parseInt(verse.split("-")[0], 10);
      const verseObj = chapterObj[verse];
      const text = extractPlainText(verseObj);
      const json_blob = JSON.stringify(verseObj);
      lines.push(
        `INSERT INTO verses (book, chapter, verse, bible_version, content_json, plain_text) VALUES (${q(book)}, ${q(chNum)}, ${q(vNum)}, ${q(bibleVersion)}, ${q(json_blob)}, ${q(text)});`,
      );
      count++;
    }
  }
  return count;
}

function extractPlainText(verseObj) {
  // verseObj.verseObjects is the array of tokens. Concatenate text tokens
  // and word tokens, skipping markers. usfm-js verse-objects shape:
  //   { type: 'text', text: '...' }
  //   { type: 'word', text: '...', occurrence, occurrences, ... }
  //   { type: 'milestone', tag: 'zaln-s', children: [...] }
  //   { type: 'paragraph', tag: 'p' }
  const parts = [];
  const walk = (vos) => {
    for (const vo of vos || []) {
      if (vo.text) parts.push(vo.text);
      if (vo.children) walk(vo.children);
    }
  };
  walk(verseObj.verseObjects);
  return parts.join("").replace(/\s+/g, " ").trim();
}

let totalVerses = 0;
totalVerses += importVerses("ULT", sources.ULT);
totalVerses += importVerses("UST", sources.UST);
totalVerses += importVerses("UHB", sources.UHB);

// ---------- TSV resources ----------
function parseTsv(srcPath) {
  if (!existsSync(srcPath)) return { headers: [], rows: [] };
  const raw = readFileSync(srcPath, "utf8");
  const linesIn = raw.split(/\r?\n/).filter((l) => l.length > 0);
  if (linesIn.length === 0) return { headers: [], rows: [] };
  const headers = linesIn[0].split("\t");
  const rows = linesIn.slice(1).map((line) => {
    const cells = line.split("\t");
    const o = {};
    headers.forEach((h, i) => (o[h] = cells[i]));
    return o;
  });
  return { headers, rows };
}

function refParts(refRaw) {
  // 'front:intro' -> 0,0
  // '1:intro'     -> 1,0
  // '1:1'         -> 1,1
  // '1:1-3'       -> 1,1 (range collapses to first verse for indexing)
  if (!refRaw) return [0, 0];
  const [ch, vs] = refRaw.split(":");
  const chNum = ch === "front" ? 0 : parseInt(ch, 10) || 0;
  const vsNum = !vs || vs === "intro" ? 0 : parseInt(vs.split("-")[0], 10) || 0;
  return [chNum, vsNum];
}

// tn: Reference, ID, Tags, SupportReference, Quote, Occurrence, Note
let tnCount = 0;
{
  const { rows } = parseTsv(sources.tn);
  for (const r of rows) {
    if (!r.ID) continue;
    const [ch, v] = refParts(r.Reference);
    const occ = r.Occurrence === "" || r.Occurrence == null ? null : parseInt(r.Occurrence, 10) || 0;
    lines.push(
      `INSERT INTO tn_rows (id, book, chapter, verse, ref_raw, tags, support_reference, quote, occurrence, note) VALUES (${q(r.ID)}, ${q(book)}, ${q(ch)}, ${q(v)}, ${q(r.Reference)}, ${q(r.Tags || null)}, ${q(r.SupportReference || null)}, ${q(r.Quote || null)}, ${q(occ)}, ${q(r.Note || null)});`,
    );
    tnCount++;
  }
}

// tq: Reference, ID, Tags, Quote, Occurrence, Question, Response
let tqCount = 0;
{
  const { rows } = parseTsv(sources.tq);
  for (const r of rows) {
    if (!r.ID) continue;
    const [ch, v] = refParts(r.Reference);
    const occ = r.Occurrence === "" || r.Occurrence == null ? null : parseInt(r.Occurrence, 10) || 0;
    lines.push(
      `INSERT INTO tq_rows (id, book, chapter, verse, ref_raw, tags, quote, occurrence, question, response) VALUES (${q(r.ID)}, ${q(book)}, ${q(ch)}, ${q(v)}, ${q(r.Reference)}, ${q(r.Tags || null)}, ${q(r.Quote || null)}, ${q(occ)}, ${q(r.Question || null)}, ${q(r.Response || null)});`,
    );
    tqCount++;
  }
}

// twl: Reference, ID, Tags, OrigWords, Occurrence, TWLink
let twlCount = 0;
{
  const { rows } = parseTsv(sources.twl);
  for (const r of rows) {
    if (!r.ID) continue;
    const [ch, v] = refParts(r.Reference);
    const occ = r.Occurrence === "" || r.Occurrence == null ? null : parseInt(r.Occurrence, 10) || 0;
    lines.push(
      `INSERT INTO twl_rows (id, book, chapter, verse, ref_raw, tags, orig_words, occurrence, tw_link) VALUES (${q(r.ID)}, ${q(book)}, ${q(ch)}, ${q(v)}, ${q(r.Reference)}, ${q(r.Tags || null)}, ${q(r.OrigWords || null)}, ${q(occ)}, ${q(r.TWLink || null)});`,
    );
    twlCount++;
  }
}

lines.push(
  `INSERT OR REPLACE INTO book_imports (book, source_url, imported_at) VALUES (${q(book)}, ${q("docs/samples/* (manual fetch)")}, unixepoch());`,
);
lines.push("COMMIT;");

const outDir = resolve(repoRoot, "scripts/out");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, `import-${book}.sql`);
writeFileSync(outPath, lines.join("\n") + "\n");

console.log(`wrote ${outPath}`);
console.log(`  verses: ${totalVerses}`);
console.log(`  tn:     ${tnCount}`);
console.log(`  tq:     ${tqCount}`);
console.log(`  twl:    ${twlCount}`);
console.log(`  total SQL statements: ${lines.length}`);
console.log("\nApply:  cd api && npx wrangler d1 execute bible_editor --local --file=../scripts/out/import-" + book + ".sql");
